theme: jekyll-theme-merlot
title: The Hepfer Family
description:  Decendents of George Jacob Hepfer and Mary Ann Walter.
show_downloads: false
menu:
  item1:
    url: "/"
    text: "Home"
  item2:
    url: "/briefHistory"
    text: "Brief History"
  item3:
    url: "/generations"
    text: "Generations"
  item4:
    url: "/pictures"
    text: "Pictures"
  item5:
    url: "/reunion"
    text: "Annual Reunion"
    
